### ISSUE TITLE
x86 application problem with ntdll.dll

### ISSUE THREAD

**Issue by KoMaR1911** [Akaion/Bleak#11]
i have problem with 
GetNtDllAddress (SyscallManager.cs) - 
return Process.GetCurrentProcess().Modules.Cast<ProcessModule>().First(module => module.ModuleName.Equals("ntdll.dll")).BaseAddress;

when i compile at x86 application have problems because app get address to x64 ntdll.dll loaded in application i need to compile at x64 to fix this issue

Thanks.

**Comment by Akaion** [comment]
Fixed in the next update that should come out soon. Thanks for pointing this out.
