### ISSUE TITLE
'Failed to query the remote process for the address of the WOW64 PEB with error code 0'

### ISSUE THREAD

**Issue by Gino** [Akaion/Bleak#16]
Hi there,

I am currently trying to inject a byte array into csgo.exe but unfortunately it gives me the following error when I try to execute that part of my code. I have no clue why this happens.

`System.ComponentModel.Win32Exception: 'Failed to query the remote process for the address of the WOW64 PEB with error code 0'`

It might be an issue with the byte array that I try to inject, not sure.

I hope you are able to help me out here.

**Comment by Akaion** [comment]
Hi,

If it would be possible could you send me your DLL? My discord is Quin#4576.

I am currently working on update 3.0 for this library which will introduce a huge amount of changes and a few bug fixes so it may be worth waiting for that to come out.
