### ISSUE TITLE
Feature request: Stealthier memory permissions

### ISSUE THREAD

**Issue by mfaerevaag** [Akaion/Bleak#17]
Hey @Akaion, exciting followin the project.

Correct me if I'm wrong, but currently Bleak are just allocating memory with RWX permissions, like [here](https://github.com/Akaion/Bleak/blob/0713730a970344b61fde44b0b05fdc41ad76c10f/Bleak/Memory/MemoryManager.cs#L28), right?

If so, this is typically what EDR solution look for on endpoints, so I think it would be a nice improvement to first allocate the memory with RW, and after copying over the data, change the permissions to RX.

What do you think?

**Comment by Akaion** [comment]
Already implemented in the 3.0 release :)) (currently in development)

**Comment by mfaerevaag** [comment]
Awesome! Looking forward to using this on red-team engagements
