### ISSUE TITLE
Parsing WOW64 insider preview wntdll pdb fails

### ISSUE THREAD

**Issue by luk1337** [Akaion/Bleak#21]
Looks like an exception is getting thrown right here https://github.com/Akaion/Bleak/blob/a246958c54440ba6a39ea3829a016e617bf0678c/Bleak/ProgramDatabase/PdbFile.cs#L137

http://msdl.microsoft.com/download/symbols/wntdll.pdb/d83d1c3722bdde7415892bd3c509c7ff1/wntdll.pdb

**Comment by Akaion** [comment]
Thanks for reporting this. I've found that there's some fundamental flaws with way I am doing the pdb parsing at the moment and will need to rewrite it (which will fix this problem.) I can't give a timeframe as to when this will be completed but it will be in the next release.

**Comment by Akaion** [comment]
@luk1337 Is there anyway I can send you my development version? I've re written the PDB parser and it seems to work my I would just like to confirm it in an actual environment that is using the new PDB's (I don't have Windows preview installed,) before I push through a patch

**Comment by luk1337** [comment]
If you send a .patch file, I can apply it.
`git format-patch -1`

**Comment by Akaion** [comment]
@luk1337 Here you go. Give it a try and let me know how it goes.

[Patch.zip](https://github.com/Akaion/Bleak/files/3505329/Patch.zip)

**Comment by luk1337** [comment]
it works ^.^
![image](https://user-images.githubusercontent.com/6830979/63091906-3a74a780-bf60-11e9-9d73-534e6ce7a1f7.png)

**Comment by Akaion** [comment]
Awesome! Was actually a lot easier to re write than I initially expected hence the quick patch. I'll push it through officially in a few minutes.

Thanks again for reporting this, would of never suspected the problem the problem otherwise :))
