### ISSUE TITLE
Deject -> Failed to call the entry point of the DLL in the remote process

### ISSUE THREAD

**Issue by Symbai** [Akaion/Bleak#24]
After blocking internet connection for bleak as workaround for #22 the injection seems successful but on deject I received an exception. The message however confuses me because on injection it successfully? has called the entry point. Why does it call the entry point another time on deject and why does it fails?

Exception:
```
Bleak.Shared.Exceptions.RemoteFunctionCallException
  HResult=0x80131500
  Message=Failed to call the entry point of the DLL in the remote process
  Source=Bleak
  StackTrace:
   at Bleak.Injection.Extensions.EjectDll.Call(IntPtr remoteDllAddress)
   at Bleak.Injection.InjectionManager.EjectDll()
   at Bleak.Injector.EjectDll()
```
Code:
```
using (var injector = new Injector("process_uwp", path, InjectionMethod.ManualMap, InjectionFlags.None))
{
    // Inject the DLL into the remote process

    var dllBaseAddress = injector.InjectDll();

    // Eject the DLL from the process

    injector.EjectDll();
}
```

**Comment by Akaion** [comment]
Entry point is called on ejection with DLL_PROCESS_DETACH. 

Ejecting DLL's isn't perfect and there's a few bugs that I need to fix so I'll take a proper look at this tomorrow

**Comment by Akaion** [comment]
Probably a good idea to indicate that the entry point is being called with DLL_PROCESS_ATTACH / DLL_PROCESS_DETACH - Will be incorporated into next release
