### ISSUE TITLE
Request: Get exported functions

### ISSUE THREAD

**Issue by Symbai** [Akaion/Bleak#25]
Some dlls have export functions. It would be great to get their memory address after injecting them with bleak using manualmap so we can call them using createremotethread.

//edit: Using manualmap symbol handlers don't find the symbols like they do when injecting with createthread so the injector would need to provide these information.

**Comment by Akaion** [comment]
Injecting returns the base address of the DLL mapped into memory. If you didn't randomise the headers, they will be there so you can parse them yourself and get the address of any exported function.
