### ISSUE TITLE
pass data to injected dll

### ISSUE THREAD

**Issue by TechInterMezzo** [Akaion/Bleak#3]
Could you add a method for invoking a remote thread/method and passing a custom parameter?
I would like to pass a dynamically generated name for a named pipe.
Or is there already something like that implemented that I missed? It looks like the needed methods are only internal.

I don't want to use a constant pipe name. That way every injector has his own communication channel. Or do you have any other idea to solve this?

**Comment by Akaion** [comment]
I'm not really sure I understand what you mean. Could you be more clear on what it is that you want added? Are you talking about calling methods from the injected DLL with optional parameters? I'm also not quire sure by what by what you mean about injectors having their own communication channel. Maybe give me an example of what you would like to do in code.

**Comment by TechInterMezzo** [comment]
I want to create an injector that has a gui and injects dlls into other processes. It listens on a named pipe and the injected dll connects to that pipe. It's basically ipc between injector and injected dll. The injector receives events and sends commands. I want to use a unique name for every named pipe to avoid collisions. For that I would have to tell the injected dll which named pipe it must connect to.

But nevermind, I just got the simple idea to use the process id for pipe name generation.

Sorry that I can't explain it clearly.
