### ISSUE TITLE
ParseExportedFunctions nullpointer exception 

### ISSUE THREAD

**Issue by Martinii89** [Akaion/Bleak#35]
This line was throwing an exception for me.
https://github.com/Akaion/Bleak/blob/003883f28ba2ac06bfccec3bcc017a9edbd8bd0d/Bleak/PortableExecutable/PeImage.cs#L187

I fixed it by doing this
```
var f = exportedFunctions.Find(exportedFunction => exportedFunction.Ordinal == exportedFunctionOrdinal);
if ( f != null)
{
    f.Name = exportedFunctionName;
}
```

I don't know why the issue with my dll was, but this seemed like a easy fix, and the injection went fine afterwards.

**Comment by Akaion** [comment]
As mentioned in the readme I am no longer going to be maintaining this library and so will not officially push through a fix, however, the new library that I am currently developing has this issue and many others fixed (on top of additional features.) I recommend you switch to that when it is released.

Never the less thanks for pointing this out.
