### ISSUE TITLE
Managed Injection

### ISSUE THREAD

**Issue by dbelz** [Akaion/Bleak#7]
Hey,

if you remember you send me a pull request regarding my dll injector (FreeLibrary) etc. 
Do you plan to support managed injection?

Greetings,
Daniel

**Comment by Akaion** [comment]
Probably not going to be supported in this library due to the differences needed. Might, at some stage create a new library for this purpose

**Comment by LegitSoulja** [comment]
@Akaion Hey, what about native injection? Is that possible in this current state, with byte array. Thanks.

**Comment by Akaion** [comment]
@LegitSoulja yes it is possible. It is explained in the documentation

**Comment by LegitSoulja** [comment]
@Akaion Couldn't make out exactly what's Native, and the docs seems a bit outdated. Is it the `Nt` prefixed methods? 

Also, when injecting with a byte array, the "temporary" dll file made in `%appdata%/Bleak` isn't free'd / un-linked after injected. Not for sure if this is supposed to happen, or if there's another method I should use but I thought the file wouldn't exist after injected. Even after many of my own attempts before I used this library, I never been able to make this possible, and if it's even possible to accomplish. Also tried some other things "Native/Unmanaged" to free/unlink however, all the attempts I've tried still showed that module, and dll path in the process. :/

**Comment by Akaion** [comment]
@LegitSoulja sorry I don't understand what your talking about. What about the docs are outdated? They are updated every time a significant change is made.

Also if you read the documentation properly, it explicitly states that byte array injection creates a file if the method is not manual mapping. If you do use the manual mapping then no temporary file is created and the DLL is injected purely from the provided byte array. Note that this only applies if you are using the latest version of the library

**Comment by LegitSoulja** [comment]
@Akaion Sorry, I was thinking the docs was outdated a bit due to the version I was using. I pulled it last week. However just updated.

**Comment by LegitSoulja** [comment]
@Akaion Sorry again for bumping this issue. I'm having issues with manual mapping. When trying to inject it fails, and says the file couldn't be found. Any idea why I am getting this error? Thanks.
