### ISSUE TITLE
AccessViolationException

### ISSUE THREAD

**Issue by dennyisfuckingnigger** [Akaion/Bleak#9]
Using the ManualMapping method like this :
 injector.ManualMap(p.Id, module);
I am getting AccessViolationException, even when running as administrator.

**Comment by Akaion** [comment]
You gotta give me more info than that....

What did you compile as?

Are you using .Net Core or .Net Framework (if so what version)

What process are you injecting into?

Does the process you are injecting into use a kernel-mode anti-cheat?

Does your DLL inject using any of the other methods?

**Comment by dennyisfuckingnigger** [comment]
Im compiling as Any CPU
Im using .NET Framework 4.6.1, was using 4.5.2, but NuGet wasnt able to download it on that version.
Im injecting into hl2.exe (Team Fortress 2)
It doesnt use ring0 anticheat, it uses VAC which is ring3
Ive tried using manualmapping and createremotethread, but everytime i get AccessViolationException says that the memory is corrupted. Im 100% sure the DLL is alright, because if i inject with GameOwner it does just fine.

**Comment by Akaion** [comment]
Hmm, I'm unable to replicate your problem with a numerous amount of processes (inlcuding VAC protected processes.) It may be worth noting that all my testing is done with the latest version of .Net Core.

Honestly, its hard to say what's causing that exception without being able to step through the code. 

Are you using the latest version of the library? There were some bugs in older versions of the library that could be causing issues like that occur.

What does `module` refer to? A string (file path of DLL) or a byte array representing the DLL?

**Comment by dennyisfuckingnigger** [comment]
Im using the latest version of the library, that can be found on NuGet. module refers to a byte array.

**Comment by Akaion** [comment]
It might be worth testing if you can first inject with a file path. There might be a problem with how you are getting the bytes of the DLL.

**Comment by dennyisfuckingnigger** [comment]
I cant still inject with file path, how i get the bytes is completely fine. It says something about Memory of the program being corrupted when it hits the inject function. I dont do anything that could fuck up the memory.

**Comment by Akaion** [comment]
Hmm I might know the problem. Do you know if your DLL uses TLS callbacks by any chance? I was adding some features last night and realised there was a bug with x86 TLS callbacks that would of caused an error like that.

**Comment by dennyisfuckingnigger** [comment]
I dont use any TLS callbacks in the DLL. Im really giving up, maybe i could send you some code in private if you need any more information or so?

**Comment by Akaion** [comment]
Yeah sure. You can add me on Discord if you want - Quin#4576
